---
- hosts: jupyterhub_hosts
  tasks:
    - command: echo "$PATH"
      register: default_path

- hosts: jupyterhub_hosts
  roles:
    - common
    - python
    - { role: newrelic, when: newrelic_license_key is defined and newrelic_license_key != ''}
    - nginx
    - supervisor
    - saveusers
    - bash
    - jupyterhub
    - { role: cull_idle, when: use_cull_idle_servers}
    - nbgrader
  environment:
      PATH: "/opt/conda/bin:{{ default_path.stdout }}"
