---
    
- hosts: jupyterhub_hosts
  remote_user: root
  
  roles:
    - common
    - python
    - node
    - { role: newrelic, when: newrelic_license_key is defined and newrelic_license_key != ''}
    - newrelic
    - nginx
    - supervisor
    - jupyterhub
    - nbgrader
    - bash
    # - R
