---

- name: JupyterHub conda dependencies
  conda: name={{item}} state=present
  become: true
  with_items:
    - configurable-http-proxy
    - sqlalchemy

- name: pip install jupyterhub
  pip: name={{item}} state=present editable=false
  become: true
  with_items:
    - git+https://github.com/jupyterhub/jupyterhub#egg=jupyterhub
    - oauthenticator==0.5
