---

# Using the npm ansible module doesn't work!!!
- name: npm install configurable-http-proxy
  command: npm install -g jupyter/configurable-http-proxy
  become: true

- name: pip install 
  pip: name={{item}} state=present executable=pip3 editable=false
  become: true
  with_items:
    # Use this branch until all the adduser PRs are merged.
    - git+https://github.com/ellisonbg/jupyterhub@adduser-fixes#egg=jupyterhub
    # - git+https://github.com/minrk/jupyterhub@adduser#egg=jupyterhub
    # - git+https://github.com/jupyter/jupyterhub#egg=jupyterhub
    - git+https://github.com/jupyter/oauthenticator#egg=oauthenticator
