---

- name: make sure base exists
  file: path={{home_dir}}/{{item[0].owner}}/nbgrader/{{item[0].course_id}}/ state={{item[1]}} owner={{item[0].owner}} mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['directory', 'touch']

- name: make sure subdirectories exist
  file: path={{home_dir}}/{{item[0].owner}}/nbgrader/{{item[0].course_id}}/{{item[1]}}/ state=directory owner={{item[0].owner}} mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['source', 'release', 'feedback', 'autograded', 'submitted']

- name: install nbgrader config file
  template: src=nbgrader_config.py.j2 dest={{home_dir}}/{{item.owner}}/nbgrader/{{item.course_id}}/nbgrader_config.py owner={{item.owner}} mode=700
  become: true
  with_items:
    - "{{nbgrader_courses}}"

- name: install supervisor config for nbgrader
  template: src=nbgrader.conf.j2 dest=/etc/supervisor/conf.d/nbgrader_{{item.course_id}}.conf owner=root group=root mode='0600' backup=yes
  become: true
  with_items:
    - "{{nbgrader_courses}}"

- name: load nbgrader supervisor config
  supervisorctl: name=nbgrader_{{item.course_id}} state=present
  become: true
  with_items:
    - "{{nbgrader_courses}}"

- name: start nbgrader with supervisor
  supervisorctl: name=nbgrader_{{item.course_id}} state=restarted
  become: true
  with_items:
    - "{{nbgrader_courses}}"