---

- name: pip install 
  pip: name={{item}} state=latest executable=pip3 editable=false
  become: true
  with_items:
    - nbgrader
    # this doesn't work currently as nbgrader is based on flit
    # - git+https://github.com/jupyter/nbgrader.git@master#egg=nbgrader

- name: make sure /var/log/nbgrader exists
  file: path={{nbgrader_log_dir}}/ state={{item}} owner=root group=root mode=0755
  become: true
  with_items:
    - directory
    - touch

- name: make sure /srv/nbgrader/exchange exists
  file: path={{nbgrader_exchange_dir}}/ state={{item}} owner=root group=root mode=0733
  become: true
  with_items:
    - directory
    - touch

- name: install the nbgrader extension
  command: nbgrader extension install
  become: true
